const columnasVisibles = [
  'FechaInicio',
  'Grupo',
  'Periodo',
  'Semana',
  'Frescura',
  'CodigoSAP',
  'Descripcion',
  'AreaReporte',
  'AreaAfecta',
  'Equipo',
  'Estacion',
  'CausaPrincipal',
  'DetalleCausa',
  'Tiempo',
  'Usuario',
  'Comentario',
  'Hr',
  'Min',
  'Seg',
  'TiempoParoTotal',
  'Programado',
  'TiempoMuerto',
  'TMCambioProducto',
  'CambioFormato',
  'LimpiezaProgramadaTM',
  'TiempoMuertoTotalHR',
  'TProgramado',
  'Tecnologia',
  'EquipoEspecifico',
  'Linea',
  'D',
  'M',
  'A',
  'AuxiliarAsignarTM'
];

const encabezados = {
  FechaInicio: 'Fecha',
  Grupo: 'Grupo',
  Periodo: 'Periodo',
  Semana: 'Semana',
  Frescura: 'Frescura',
  CodigoSAP: 'Código SAP',
  Descripcion: 'Descripción',
  AreaReporte: 'Área que reporta',
  AreaAfecta: 'Área que afecta',
  Equipo: 'Equipo',
  Estacion: 'Estación / Segmento',
  CausaPrincipal: 'Causa Principal',
  DetalleCausa: 'Detalle de la causa',
  Tiempo: 'Tiempo Registrado',
  Usuario: 'Usuario',
  Comentario: 'Comentarios',
  Hr: 'Horas',
  Min: 'Minutos',
  Seg: 'Segundos',
  TiempoParoTotal: 'Tiempo de Paro Total',
  Programado: '¿Programado?',
  TiempoMuerto: 'Tiempo Muerto',
  TMCambioProducto: 'TM Cambio Producto',
  CambioFormato: 'Cambio de Formato',
  LimpiezaProgramadaTM: 'Limpieza Programada TM',
  TiempoMuertoTotalHR: 'Tiempo Muerto Total (HR)',
  TProgramado: 'T. Programado',
  Tecnologia: 'Tecnología',
  EquipoEspecifico: 'Equipo Específico',
  Linea: 'Línea',
  D: 'D',
  M: 'M',
  A: 'A',
  AuxiliarAsignarTM: 'Auxiliar Asignar TM'
};

export { columnasVisibles, encabezados };